server:
  tomcat:
    accesslog:
      directory: d:\log
      enabled: true
wiesel:
  uploadPath: D:/var/uploaded_files/
logging:
  level:
    root: info
    com.wiesel: debug
swagger :
   enabled: true
spring:
  # ====================druid====================
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.201.218:3306/wiesel?useUnicode=true&characterEncoding=utf8&&allowMultiQueries=true
    username: root
    password: 123456
    #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
    initialSize: 1
    #最小连接池数量
    minIdle: 3
    #最大连接池数量
    maxActive: 20
    #配置获取连接等待超时的时间
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    #验证连接有效与否的SQL，不同的数据配置不同
    validationQuery: select 'x'
    #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，
    #如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    #这里建议配置为TRUE，防止取到的连接不可用
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
    #常用的插件有： 监控统计用的filter:stat,日志用的filter:log4j,防御sql注入的filter:wall
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
    
  # ====================redis====================
  redis:
      host: 47.98.201.218
      port: 6379
      password:
      # 连接超时时间（毫秒）
      timeout: 10000
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        
# ====================MybatisPlus====================
mybatisPlus:
  #typeEnumsPackage: com.wiesel.common.enums
  #typeHandlersPackage : com.wiesel.common.enums.handler
  globalConfig:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    idType: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    fieldStrategy: 2
    #驼峰下划线转换
    dbColumnUnderline: true
    #刷新mapper 调试神器
    refreshMapper: true
    #数据库大写下划线转换
    capital-mode: true
    #逻辑删除配置
    logicDeleteValue: 0
    logicNotDeleteValue: 1
